name: Java CI

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '21'
            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v3
                with:
                    gradle-version: wrapper
            -   name: Build with Gradle
                run: ./gradlew build
            -   name: Upload coverage to Codecov
                if: matrix.os == 'ubuntu-latest'
                uses: codecov/codecov-action@v4
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    fail_ci_if_error: true
                    verbose: false
